## TEXT CLASSIFICATION USING NAIVE BAYES:

In [1]:
import numpy as np
import os
import pandas as pd

## Extracting X and Y from the given DATASET:

In [2]:
# stopwords = ['a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and', 'any', 'are', "aren't", 'as', 'at',
#  'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 
#  'can', "can't", 'cannot', 'could', "couldn't", 'did', "didn't", 'do', 'does', "doesn't", 'doing', "don't", 'down', 'during',
#  'each', 'few', 'for', 'from', 'further', 
#  'had', "hadn't", 'has', "hasn't", 'have', "haven't", 'having', 'he', "he'd", "he'll", "he's", 'her', 'here', "here's",
#  'hers', 'herself', 'him', 'himself', 'his', 'how', "how's",
#  'i', "i'd", "i'll", "i'm", "i've", 'if', 'in', 'into', 'is', "isn't", 'it', "it's", 'its', 'itself',
#  "let's", 'me', 'more', 'most', "mustn't", 'my', 'myself',
#  'no', 'nor', 'not', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'ought', 'our', 'ours' 'ourselves', 'out', 'over', 'own',
#  'same', "shan't", 'she', "she'd", "she'll", "she's", 'should', "shouldn't", 'so', 'some', 'such', 
#  'than', 'that',"that's", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', "there's", 'these', 'they', "they'd", 
#  "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 'very', 
#  'was', "wasn't", 'we', "we'd", "we'll", "we're", "we've", 'were', "weren't", 'what', "what's", 'when', "when's", 'where',
#  "where's", 'which', 'while', 'who', "who's", 'whom', 'why', "why's",'will', 'with', "won't", 'would', "wouldn't", 
#  'you', "you'd", "you'll", "you're", "you've", 'your', 'yours', 'yourself', 'yourselves', 
#  'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'hundred', 'thousand', '1st', '2nd', '3rd',
#  '4th', '5th', '6th', '7th', '8th', '9th', '10th']

## Loading Stopwords:

In [10]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords = set(stopwords.words('spanish'))

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [12]:
stopwords

{'a',
 'al',
 'algo',
 'algunas',
 'algunos',
 'ante',
 'antes',
 'como',
 'con',
 'contra',
 'cual',
 'cuando',
 'de',
 'del',
 'desde',
 'donde',
 'durante',
 'e',
 'el',
 'ella',
 'ellas',
 'ellos',
 'en',
 'entre',
 'era',
 'erais',
 'eran',
 'eras',
 'eres',
 'es',
 'esa',
 'esas',
 'ese',
 'eso',
 'esos',
 'esta',
 'estaba',
 'estabais',
 'estaban',
 'estabas',
 'estad',
 'estada',
 'estadas',
 'estado',
 'estados',
 'estamos',
 'estando',
 'estar',
 'estaremos',
 'estará',
 'estarán',
 'estarás',
 'estaré',
 'estaréis',
 'estaría',
 'estaríais',
 'estaríamos',
 'estarían',
 'estarías',
 'estas',
 'este',
 'estemos',
 'esto',
 'estos',
 'estoy',
 'estuve',
 'estuviera',
 'estuvierais',
 'estuvieran',
 'estuvieras',
 'estuvieron',
 'estuviese',
 'estuvieseis',
 'estuviesen',
 'estuvieses',
 'estuvimos',
 'estuviste',
 'estuvisteis',
 'estuviéramos',
 'estuviésemos',
 'estuvo',
 'está',
 'estábamos',
 'estáis',
 'están',
 'estás',
 'esté',
 'estéis',
 'estén',
 'estés',
 'fue',
 'f

In [7]:
directory=[i for i in os.listdir('./20_newsgroups/')]

NameError: name 'os' is not defined

In [5]:
directory

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

## Making Dictionary of words and there Frequency(ex.{'cool':256,'root':4569}):

In [6]:
result={}
for i in range(len(directory)):
    files=os.listdir('./20_newsgroups/' + directory[i])
    for j in range(len(files)):
        path='./20_newsgroups/'+directory[i]+'/'+files[j]
        text=open(path,'r',errors='ignore').read()
        for k in text.split():
            if(len(k)!=1):
                if( not k.lower() in stopwords):
                    if(result.get(k.lower()) != None):
                        result[k.lower()]+=1
                    else:
                        result[k.lower()]=1

## Sorting the dictionary and taking top 2000 words with highest frequency


In [7]:
import operator
sorted_result = sorted(result.items(), key=operator.itemgetter(1),reverse=True)

In [8]:
result1={}
a=sorted_result[2000][1]
for i in sorted_result:
    result1[i[0]]=i[1]
    if(i[1]<a):
        break

In [9]:
feature=list(result1.keys())

## Process of Loading the data into a dataFrame:

In [10]:
df=pd.DataFrame(columns=feature)

In [11]:
for i in range(len(directory)):
    files=os.listdir('./20_newsgroups/'+directory[i])
    for j in range(len(files)):
        path='./20_newsgroups/'+directory[i]+'/'+files[j]
        text=open(path,'r',errors='ignore').read()
        df.loc[len(df)] = np.zeros(len(feature))
        for k in text.split():
            if(k.lower() in feature):
                df[k.lower()][len(df)-1]+=1

In [12]:
df.head(20)

from:  subject:  date:  newsgroups:  message-id:  path:  lines:  apr  \
0     1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
1     1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
2     1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
3     1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
4     1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
5     1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
6     1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
7     1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
8     1.0       1.0    1.0          1.0          1.0    1.0     1.0  2.0   
9     1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
10    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
11    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
12    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
13    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
14    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
15    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
16    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
17    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
18    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   
19    1.0       1.0    1.0          1.0          1.0    1.0     1.0  1.0   

    organization:  gmt   ...     *****  compound  playoff  pit-6  crypto  \
0             1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
1             1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
2             1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
3             1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
4             0.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
5             1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
6             1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
7             1.0  0.0   ...       0.0       0.0      0.0    0.0     0.0   
8             1.0  2.0   ...       0.0       0.0      0.0    0.0     0.0   
9             1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
10            1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
11            1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
12            1.0  0.0   ...       0.0       0.0      0.0    0.0     0.0   
13            1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
14            1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
15            1.0  0.0   ...       0.0       0.0      0.0    0.0     0.0   
16            1.0  0.0   ...       0.0       0.0      0.0    0.0     0.0   
17            1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
18            1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   
19            1.0  1.0   ...       0.0       0.0      0.0    0.0     0.0   

    scientists  spacecraft  greeks  constitution  funding  
0          0.0         0.0     0.0           0.0      1.0  
1          0.0         0.0     0.0           0.0      0.0  
2          0.0         0.0     0.0           0.0      0.0  
3          0.0         0.0     0.0           0.0      0.0  
4          0.0         0.0     0.0           0.0      0.0  
5          0.0         0.0     0.0           0.0      0.0  
6          0.0         0.0     0.0           0.0      0.0  
7          0.0         0.0     0.0           0.0      0.0  
8          0.0         0.0     0.0           0.0      0.0  
9          0.0         0.0     0.0           0.0      0.0  
10         0.0         0.0     0.0           0.0      0.0  
11         0.0         0.0     0.0           0.0      0.0  
12         0.0         0.0    

## Extract X and Y from data and Split it into Training and testing Data:

In [13]:
x=df.values

In [14]:
y=[]
for i in range(len(directory)):
    files=os.listdir('./20_newsgroups/'+directory[i])
    for j in range(len(files)):
        y.append(i)
y=np.array(y)

In [15]:
y.shape,x.shape

((2000,), (2000, 2075))

In [16]:
from sklearn import model_selection
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size = 0.25, random_state = 1)

## Multinomial NaiveBayes From Sklearn:

In [17]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB()
clf.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [18]:
y_predict=clf.predict(x_test)
print("Train_score =",clf.score(x_train, y_train))
Test_score =clf.score(x_test, y_test)
print(Test_score)

Train_score = 0.9266666666666666
0.7


## Multinomial NavieBayes From Scratch:

In [19]:
f=list(df)

#### Making dictionary of words and there Frequency:

In [20]:
def fit(x_train,y_train):
    result={}
    class_count=set(y_train)
    for current_class in class_count:
        t=(y_train == current_class)
        x_curr=x_train[t]
        y_curr=y_train[t]
        result["total_data"]=len(y_train)
        sum=0
        result[current_class]={}
        for i in range(len(f)):
            result[current_class][f[i]]=x_curr[:,i].sum()
            sum=sum+result[current_class][f[i]]
        result[current_class]["total_count"]=sum
    return result

#### Finding the Probability:

In [21]:
def probability(dictionary, x, current_class):
    class_prob = np.log(dictionary[current_class]["total_count"]) - np.log(dictionary["total_data"])
    total_prob = class_prob
    for i in range(len(x)):
        word_count = dictionary[current_class][f[i]] + 1     
        total_count = dictionary[current_class]["total_count"] + len(f)
        word_prob = np.log(word_count) - np.log(total_count)
        for j in range(int(x[i])):
            total_prob += word_prob
    return total_prob

#### Predicting the which class data belong:

In [22]:
def predictSinglePoint(dictionary,x):
    classes=dictionary.keys()
    best_prob=-1000
    best_class=-1
    first_run=True
    for current_class in classes:
        if(current_class == "total_data"):
            continue
        prob=probability(dictionary,x,current_class)
        if(first_run or prob>best_prob):
            best_prob=prob
            best_class=current_class
        first_run=False
    return best_class

In [23]:
def predict(dictionary,x_test):
    y_predict1=[]
    for i in range(len(x_test)):
        pred=predictSinglePoint(dictionary,x_test[i,:])
        y_predict1.append(pred)
    return y_predict1

In [24]:
dictionary=fit(x_train,y_train)

#### Result of prediction from scratch

In [25]:
y_predict1=predict(dictionary,x_test)

## Result Comparision:

In [26]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print("Sklearn Result")
print("score:",Test_score)
print(confusion_matrix(y_test,y_predict))
print()
print("From Scratch")
print("score:",accuracy_score(y_test, y_predict1))
print(confusion_matrix(y_test,y_predict1))

Sklearn Result
score: 0.7
[[17  0  1  0  0  0  0  0  1  1  0  0  0  0  0  0  0  0  0  3]
 [ 0  6  5  5  2  3  2  1  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0 22  2  0  0  1  0  0  0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3 21  2  0  1  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 18  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  2  4  2  0 18  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  1  0  0  0 24  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2 17  2  1  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  1  4 20  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1 27  1  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  1  0  3 22  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  1  1  0  0 16  0  0  0  0  0  0  2  0]
 [ 0  0  0  2  1  0  7  4  2  1  0  1 12  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  2  0  0  0  0 14  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  1  1  0  0  0  0  0 19  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 